accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'
urlpatterns=[
			path('register', views.register, name='register'),
			path('login', views.login, name='login'),
			path('logout', views.logout, name='logout'),

]

credit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('home.urls', namespace='home')),
    path('loan/',include('loan_approval.urls', namespace='loan')),
    path('about/',include('about.urls', namespace='about')),


]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
			path('', views.home, name='homepage'),


]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Home {% endblock %}</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="/" class="probootstrap-logo">Creditfy<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            

            {% if user.is_authenticated %}
  
            <li {% if register_form %}class="active"{% endif %}>Welcome! {{user.first_name}}</li>
            <li {% if register_form %}class="active"{% endif %}><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li {% if register_form %}class="active"{% endif %}><a href="{% url 'accounts:register' %}">Register</a></li>
            <li {% if login_form %}class="active"{% endif %}><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>
  <!-- END: header -->


  {% block body %}

  {% endblock %}


  


  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  <script src="{% static 'js/scripts.min.js' %}"></script>
  <script src="{% static 'js/main.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script>
    $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2012",
      // You can put more options here.

    });
  });
  </script>
  </body>
</html>