about/urls.py
from django.urls import path 
from . import views
app_name='about'

urlpatterns=[
				path('', views.about_us, name='info')
]

credit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('',include('home.urls', namespace='home')),
    path('loan/',include('loan_approval.urls', namespace='loan')),
    path('about/',include('about.urls', namespace='about')),


]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
			path('', views.home, name='homepage'),


]

about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
	title=models.CharField(max_length=70)
	sub_title=models.CharField(max_length=70)
	description=models.TextField()
	image=models.ImageField(upload_to='about')

	def __str__(self):
		return self.title

	class Meta:
		verbose_name='About Company'
		verbose_name_plural='About Company'

about/views.py
from django.shortcuts import render
from .models import About


# Create your views here.


def about_us(request):
	info = About.objects.all()

	template='about/aboutus.html'

	context={
				'info':info,
	}

	return render(request, template, context)

about/templates/about/aboutus.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}


{% block body %}
  <!-- END: header -->

<section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'about:info' %}">About</a></span>
              </div>
              <h1>About Us</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
</section>
  <!-- END: slider  -->

{% for information in info %}


{% if forloop.counter|divisibleby:2 %}

	<section class="probootstrap-half reverse">
    <div class="image-wrap">
      <div class="image" style="background-image: url({{information.image.url}});"></div>
    </div>
     <div class="text">
      <p class="mb10 subtitle">{{information.sub_title}}</p>
      <h3 class="mt0 mb40">{{information.title}}</h3>
      <p>{{information.description}}</p>
      <p><a href="#" class="btn btn-primary mb10">Find out more</a></p>
    </div>
	</section>

{% else %}
	<section class="probootstrap-half">
    <div class="image-wrap">
      <div class="image" style="background-image: url({{information.image.url}});"></div>
    </div>
    <div class="text">
      <p class="mb10 subtitle">{{information.sub_title}}</p>
      <h3 class="mt0 mb40">{{information.title}}</h3>
      <p>{{information.description}}</p>
      <p><a href="#" class="btn btn-primary mb10">Find out more</a></p>
    </div>
</section>

{% endif %}

{% endfor %}
{% endblock %}

 